v1.13.0
ros-noetic-arch/ros-noetic-control-toolbox pull request #1
Opened 2020-12-07 15:04 UTC by nim65s

Hi,

This is an update following https://github.com/ros/rosdistro/blob/4fbed76b297a148cd5ec7f7f3a882a28e02005c6/noetic/distribution.yaml#L1022

2020-12-07 15:32 UTC, bionade24 requested changes
Please reset `pkgrel` after updates. You can use https://github.com/ros-arch/ros-aur-helpers to update the PKGBUILDs automatically.

2020-12-07 15:32 UTC, bionade24 commented on PKGBUILD
>  pkgrel=2
Wrong, `pkgrel` needs to be reset to 1

2020-12-07 15:36 UTC, bionade24 commented
Please use `git commit --amend` instead of making a new commit, otherwise the AUR will reject it becase there isn't one version increase per commit. If we otherwise forget to squash merge it will be fucked up.

2020-12-07 15:50 UTC, nim65s commented
Thanks for the review and the tips !

2020-12-07 16:05 UTC, bionade24 approved these changes

2020-12-08 00:05 UTC, acxz approved these changes

2020-12-08 00:05 UTC, merged